### ISSUE TITLE
No sound in Chrome for OSX

### ISSUE THREAD

**Issue by CeliaCha** [paulrosen/vue-abcjs-midi-demo#3]
Hi and thanks for this nice library.
Works well with Firefox but Impossible to play sound in Chrome for OSX (v 65.0.3325.18). Audio control seems to be disabled by default.

**Comment by paulrosen** [comment]
I just tried it on a MacBookPro with that version of Chrome and it played by simply pressing the "play" button.

I'm running OS X El Capitan (10.11.6) What OS do you have?

When you say "Audio control seems to be disabled by default" what do you mean? When you hover over the play button it should change color a little bit. If you use the tab key, you should get a "focus" element on the textarea and on three parts of the audio control. When you click the "play" button it should change to a "pause" button.

**Comment by paulrosen** [comment]
BTW, Chrome 66 imposed some rules on playing audio that broke playing in versions before v5.0.0. I put in a fix for that in v5.0.1.
