### ISSUE TITLE
generateDownload don't work

### ISSUE THREAD

**Issue by mxbastian** [paulrosen/vue-abcjs-midi-demo#5]
Hi,
this demo package works fine basically. But if I add 'generateDownload:true,' in abcjsParams it doesn't work, the Link doesn't create and the animation then doesn't work as well. What I do wrong?

  mounted: function () {
    new abcjs.Editor("abc-source", {
      canvas_id: "paper",
      generate_midi: true,
      midi_id: "midi",
      abcjsParams: {
        midiListener: this.listener,
        animate: {
          listener: this.animate,
        },
        inlineControls: {
          loopToggle: true,
          tempo: true,
        },
        generateDownload: true,
      },
    });
	},

**Comment by mxbastian** [comment]
Oh, it will create but it's hidden or not clickable. Ok, I guess this issue can get fixed with css.
But why is the animation disabled now?


![Bildschirmfoto 2022-01-06 um 18 50 50 (2)](https://user-images.githubusercontent.com/69186739/148428753-18d25678-baf3-400d-bd1e-79d4494c334a.png)
?

**Comment by paulrosen** [comment]
Hi, I haven't been keeping this demo up to date so it is using a pretty old version of the library. This is up to date: https://paulrosen.github.io/abcjs/examples/full-synth.html

It doesn't use Vue, though. If that is your goal you can merge the two demos.

I will update this example sometime soon.

**Comment by mxbastian** [comment]
Hi, thx for quick response. Do you have this full-synth demo as code example as well?

**Comment by mxbastian** [comment]
Found it. But isn't practicable for me, i have to embed the abc notation with php. I will wait till you have updated the midi demo. You can close this issue.

Best regards from Berlin, Germany
